services:
  neo4j:
    build: .
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
        # Persistência de dados
      - "./data:/data"
        # Import de arquivos de diretório no host
      - "./import:/import:ro"
        # Possibilita o uso do apoc-full
        # https://neo4j.com/docs/apoc/current/installation/
      - "./plugins:/plugins"
  chartdb:
    image: ghcr.io/chartdb/chartdb:latest
    ports:
      - "8080:80"
